In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import datetime
from helpfulfun import *
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Import the dataset

In [14]:
#### import the datasets

train_list = np.genfromtxt("train.csv", dtype=None, delimiter=",", skip_header =0, unpack=True, encoding=None)
train = np.array(train_list)

test_list = np.genfromtxt("test.csv", dtype=None, delimiter=",", skip_header =1, unpack=True, encoding=None)
test = np.array(test_list)

In [15]:
x_te = test[2:].T

In [16]:
y = train[1, 1:]
x_tr = train[2:,1: ].T.astype('float')
print("x: ", x_tr.shape, " y: ", y.shape)

x:  (250000, 30)  y:  (250000,)


In [17]:
y_tr = np.where(y == "s",1,-1)
print(y_tr.shape, " and y[:5]: ", y_tr[:5])

(250000,)  and y[:5]:  [ 1 -1 -1 -1 -1]


In [18]:
x_tr[:,22].astype(int)

array([2, 1, 1, ..., 1, 0, 0])

### Pre processing

In [19]:
for i in range(x_tr.shape[1] ):
    print(i, np.count_nonzero(abs(x_tr[:,i]) == 999.0), train[i+2, 0])


0 38114 DER_mass_MMC
1 0 DER_mass_transverse_met_lep
2 0 DER_mass_vis
3 0 DER_pt_h
4 177457 DER_deltaeta_jet_jet
5 177457 DER_mass_jet_jet
6 177457 DER_prodeta_jet_jet
7 0 DER_deltar_tau_lep
8 0 DER_pt_tot
9 0 DER_sum_pt
10 0 DER_pt_ratio_lep_tau
11 0 DER_met_phi_centrality
12 177457 DER_lep_eta_centrality
13 0 PRI_tau_pt
14 0 PRI_tau_eta
15 0 PRI_tau_phi
16 0 PRI_lep_pt
17 0 PRI_lep_eta
18 0 PRI_lep_phi
19 0 PRI_met
20 0 PRI_met_phi
21 0 PRI_met_sumet
22 0 PRI_jet_num
23 99913 PRI_jet_leading_pt
24 99913 PRI_jet_leading_eta
25 99913 PRI_jet_leading_phi
26 177457 PRI_jet_subleading_pt
27 177457 PRI_jet_subleading_eta
28 177457 PRI_jet_subleading_phi
29 0 PRI_jet_all_pt


In [25]:
#keep all except for those with many missng
x_tr_2 = np.array(np.delete(x_tr,(4,5,6,12,26,27,28), axis = 1))
train = np.array(train_list)
train = np.delete(train, (6,7,8,14,28,29,31), axis= 0)
for i in range(x_tr_2.shape[1] ):
    print(i, np.count_nonzero(abs(x_tr_2[:,i]) == 999.0), train[i+2,0])


0 38114 DER_mass_MMC
1 0 DER_mass_transverse_met_lep
2 0 DER_mass_vis
3 0 DER_pt_h
4 0 DER_deltar_tau_lep
5 0 DER_pt_tot
6 0 DER_sum_pt
7 0 DER_pt_ratio_lep_tau
8 0 DER_met_phi_centrality
9 0 PRI_tau_pt
10 0 PRI_tau_eta
11 0 PRI_tau_phi
12 0 PRI_lep_pt
13 0 PRI_lep_eta
14 0 PRI_lep_phi
15 0 PRI_met
16 0 PRI_met_phi
17 0 PRI_met_sumet
18 0 PRI_jet_num
19 99913 PRI_jet_leading_pt
20 99913 PRI_jet_leading_eta
21 99913 PRI_jet_leading_phi
22 0 PRI_jet_subleading_phi


In [11]:
#impute using median
x_tr_2[abs(x_tr_2)==999.0] = np.nan
ind = np.where(np.isnan(x_tr_2))

median = np.nanmedian(x_tr_2, axis=0, out=None, overwrite_input=False)

x_tr_2[ind] =  np.take(median, ind[1])

x_tr_2.shape


array([[ 1.38470e+02,  5.16550e+01,  9.78270e+01, ...,  2.15000e+00,
         4.44000e-01,  1.13497e+02],
       [ 1.60937e+02,  6.87680e+01,  1.03235e+02, ...,  7.25000e-01,
         1.15800e+00,  4.62260e+01],
       [ 1.12406e+02,  1.62172e+02,  1.25953e+02, ...,  2.05300e+00,
        -2.02800e+00,  4.42510e+01],
       ...,
       [ 1.05457e+02,  6.05260e+01,  7.58390e+01, ...,  1.80000e+00,
        -1.66000e-01,  4.19920e+01],
       [ 9.49510e+01,  1.93620e+01,  6.88120e+01, ...,  0.00000e+00,
        -3.30000e-02,  0.00000e+00],
       [ 1.12406e+02,  7.27560e+01,  7.08310e+01, ...,  0.00000e+00,
        -3.30000e-02,  0.00000e+00]])

In [10]:
np.isnan(x_tr_2)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [11]:
#create x_te_2
x_te_2 = np.array(np.delete(x_te,(4,5,6,12,26,27,28), axis = 1))


In [12]:
## export the dataset:
np.savetxt("x_tr_2.csv", x_tr_2, fmt="%s", delimiter=",")
np.savetxt("x_te_2.csv", x_te_2, fmt="%s", delimiter=",")

In [13]:
# let's remove the primitive variables:
x_tr_3 = x_tr_2[:,:9]
x_tr_3.shape
for i in range(x_tr_3.shape[1] ):
    print(i, np.count_nonzero(abs(x_tr_3[:,i]) == 999.0), train[i+2,0])


0 0 DER_mass_MMC
1 0 DER_mass_transverse_met_lep
2 0 DER_mass_vis
3 0 DER_pt_h
4 0 DER_deltar_tau_lep
5 0 DER_pt_tot
6 0 DER_sum_pt
7 0 DER_pt_ratio_lep_tau
8 0 DER_met_phi_centrality


In [31]:
# now impute outliers

def impute_outliers_mean(a):
    '''impute outliers with mean'''
    # 1. Determine mean and standard deviation
    mean = np.mean(a, axis = 0)
    std_dev = np.std(a, axis = 0)
    # 2. Normalize array around 0
    zero_based = abs(a - mean)
    # 3. Define maximum number of standard deviations
    max_deviations = 2
    # 4. Access only non-outliers using Boolean Indexing
    num_out = 0
    for i in range(a.shape[1]):
        for j in range(a.shape[0]):
            if zero_based[j,i] > max_deviations * std_dev[i]:
                a[j,i] = mean[i]
                num_out += 1
    print(num_out, "observations have been replaced by the corresponding mean")
    
    return a

#x_tr_3_no_out = impute_outliers_mean(x_tr_3)



In [19]:
x_te_3 = x_te_2[:,:9] 

In [20]:
## export the dataset:
np.savetxt("x_tr_3_no_out.csv", x_tr_3_no_out, fmt="%s", delimiter=",")
np.savetxt("x_te_3_no_out.csv", x_te_3, fmt="%s", delimiter=",")

In [33]:
x_tr_4 = np.array(np.delete(x_tr,(0,5,6,9,21,23,29), axis = 1))
x_te_4 = np.array(np.delete(x_te,(0,5,6,9,21,23,29), axis = 1))
train = np.array(train_list)
train = np.delete(train, (2,7,8,11,23,25,31), axis = 0)

In [34]:
for i in range(x_tr_4.shape[1] ):
    print(i, np.count_nonzero(abs(x_tr[:,i]) == 999.0), train[i+2, 0])


0 38114 DER_mass_transverse_met_lep
1 0 DER_mass_vis
2 0 DER_pt_h
3 0 DER_deltaeta_jet_jet
4 177457 DER_deltar_tau_lep
5 177457 DER_pt_tot
6 177457 DER_pt_ratio_lep_tau
7 0 DER_met_phi_centrality
8 0 DER_lep_eta_centrality
9 0 PRI_tau_pt
10 0 PRI_tau_eta
11 0 PRI_tau_phi
12 177457 PRI_lep_pt
13 0 PRI_lep_eta
14 0 PRI_lep_phi
15 0 PRI_met
16 0 PRI_met_phi
17 0 PRI_jet_num
18 0 PRI_jet_leading_eta
19 0 PRI_jet_leading_phi
20 0 PRI_jet_subleading_pt
21 0 PRI_jet_subleading_eta
22 0 PRI_jet_subleading_phi


In [35]:
#impute nan using median
x_tr_4[abs(x_tr_4)==999.0] = np.nan
ind = np.where(np.isnan(x_tr_4))

median = np.nanmedian(x_tr_4, axis=0, out=None, overwrite_input=False)

x_tr_4[ind] =  np.take(median, ind[1])

x_tr_4

array([[ 5.16550e+01,  9.78270e+01,  2.79800e+01, ...,  4.60620e+01,
         1.24000e+00, -2.47500e+00],
       [ 6.87680e+01,  1.03235e+02,  4.81460e+01, ...,  4.79020e+01,
        -1.00000e-02, -2.00000e-03],
       [ 1.62172e+02,  1.25953e+02,  3.56350e+01, ...,  4.79020e+01,
        -1.00000e-02, -2.00000e-03],
       ...,
       [ 6.05260e+01,  7.58390e+01,  3.97570e+01, ...,  4.79020e+01,
        -1.00000e-02, -2.00000e-03],
       [ 1.93620e+01,  6.88120e+01,  1.35040e+01, ...,  4.79020e+01,
        -1.00000e-02, -2.00000e-03],
       [ 7.27560e+01,  7.08310e+01,  7.47900e+00, ...,  4.79020e+01,
        -1.00000e-02, -2.00000e-03]])

In [36]:
x_tr_4_no_out = impute_outliers_mean(x_tr_4)

266964 observations have been replaced by the corresponding mean


In [37]:
np.savetxt("x_tr_4_no_out.csv", x_tr_4_no_out, fmt="%s", delimiter=",")
np.savetxt("x_te_4_no_out.csv", x_te_4, fmt="%s", delimiter=",")